---

- name: Install logrotate via apt
  apt: name=logrotate
  when: ansible_os_family == 'Debian'

- name: Install logrotate via yum
  yum: name=logrotate
  when: ansible_os_family == 'RedHat'

- name: Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined